// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;
use craby::throw;

use crate::generated::*;
use crate::hwpjs_impl::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::hwpjs::bridging")]
pub mod bridging {
    #[derive(Clone)]
    struct NullableString {
        null: bool,
        val: String,
    }

    #[derive(Clone)]
    struct ToMarkdownResult {
        markdown: String,
    }

    #[derive(Clone)]
    struct ToMarkdownOptions {
        image_output_dir: NullableString,
        image: NullableString,
        use_html: bool,
        include_version: bool,
        include_page_info: bool,
    }

    #[derive(Clone)]
    struct ToPdfOptions {
        font_dir: NullableString,
        embed_images: bool,
    }

    extern "Rust" {
        type Hwpjs;

        #[cxx_name = "createHwpjs"]
        fn create_hwpjs(id: usize, data_path: &str) -> Box<Hwpjs>;

        #[cxx_name = "createVecFromSlice"]
        fn create_vec_from_slice(data: &[u8]) -> Vec<u8>;

        #[cxx_name = "fileHeader"]
        fn hwpjs_file_header(it_: &mut Hwpjs, data: Vec<u8>) -> Result<String>;

        #[cxx_name = "toJson"]
        fn hwpjs_to_json(it_: &mut Hwpjs, data: Vec<u8>) -> Result<String>;

        #[cxx_name = "toMarkdown"]
        fn hwpjs_to_markdown(
            it_: &mut Hwpjs,
            data: Vec<u8>,
            options: ToMarkdownOptions,
        ) -> Result<ToMarkdownResult>;

        #[cxx_name = "toPdf"]
        fn hwpjs_to_pdf(it_: &mut Hwpjs, data: Vec<u8>, options: ToPdfOptions) -> Result<Vec<u8>>;
    }
}

fn create_hwpjs(id: usize, data_path: &str) -> Box<Hwpjs> {
    let ctx = Context::new(id, data_path);
    Box::new(Hwpjs::new(ctx))
}

fn create_vec_from_slice(data: &[u8]) -> Vec<u8> {
    data.to_vec()
}

#[allow(clippy::let_and_return)]
fn hwpjs_file_header(it_: &mut Hwpjs, data: Vec<u8>) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.file_header(data);
        ret
    })
}

#[allow(clippy::let_and_return)]
fn hwpjs_to_json(it_: &mut Hwpjs, data: Vec<u8>) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.to_json(data);
        ret
    })
}

#[allow(clippy::let_and_return)]
fn hwpjs_to_markdown(
    it_: &mut Hwpjs,
    data: Vec<u8>,
    options: ToMarkdownOptions,
) -> Result<ToMarkdownResult, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.to_markdown(data, options);
        ret
    })
}

#[allow(clippy::let_and_return)]
fn hwpjs_to_pdf(it_: &mut Hwpjs, data: Vec<u8>, options: ToPdfOptions) -> Result<Vec<u8>, anyhow::Error> {
    craby::catch_panic!({
        it_.to_pdf(data, options).unwrap_or_else(|e| throw!("{}", e))
    })
}
