// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::react_native_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::reactnative::bridging")]
pub mod bridging {




    extern "Rust" {
        type ReactNative;

        #[cxx_name = "createReactNative"]
        fn create_react_native(id: usize, data_path: &str) -> Box<ReactNative>;

        #[cxx_name = "add"]
        fn react_native_add(it_: &mut ReactNative, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "divide"]
        fn react_native_divide(it_: &mut ReactNative, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "hwpParser"]
        fn react_native_hwp_parser(it_: &mut ReactNative, data: Vec<f64>) -> Result<String>;

        #[cxx_name = "multiply"]
        fn react_native_multiply(it_: &mut ReactNative, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "subtract"]
        fn react_native_subtract(it_: &mut ReactNative, a: f64, b: f64) -> Result<f64>;
    }

}

fn create_react_native(id: usize, data_path: &str) -> Box<ReactNative> {
    let ctx = Context::new(id, data_path);
    Box::new(ReactNative::new(ctx))
}

fn react_native_add(it_: &mut ReactNative, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.add(a, b);
        ret
    })
}

fn react_native_divide(it_: &mut ReactNative, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.divide(a, b);
        ret
    })
}

fn react_native_hwp_parser(it_: &mut ReactNative, data: Vec<f64>) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.hwp_parser(data);
        ret
    })
}

fn react_native_multiply(it_: &mut ReactNative, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.multiply(a, b);
        ret
    })
}

fn react_native_subtract(it_: &mut ReactNative, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.subtract(a, b);
        ret
    })
}
