// Auto generated by Craby. DO NOT EDIT.
// Hash: 1761b519b16719d6
#![allow(clippy::derivable_impls)]
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

#[allow(dead_code)]
pub trait HwpjsSpec {
    #[allow(dead_code)]
    fn new(ctx: Context) -> Self;
    #[allow(dead_code)]
    fn id(&self) -> usize;
    #[allow(dead_code)]
    fn file_header(&mut self, data: ArrayBuffer) -> String;
    #[allow(dead_code)]
    fn to_json(&mut self, data: ArrayBuffer) -> String;
    #[allow(dead_code)]
    fn to_markdown(&mut self, data: ArrayBuffer, options: ToMarkdownOptions) -> ToMarkdownResult;
    #[allow(dead_code)]
    fn to_pdf(
        &mut self,
        data: ArrayBuffer,
        options: ToPdfOptions,
    ) -> Result<Vec<u8>, anyhow::Error>;
}

impl Default for NullableString {
    fn default() -> Self {
        NullableString {
            null: true,
            val: String::default(),
        }
    }
}

impl From<NullableString> for Nullable<String> {
    fn from(val: NullableString) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<String>> for NullableString {
    fn from(val: Nullable<String>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableString {
            val: val.unwrap_or_default(),
            null,
        }
    }
}

impl Default for ToMarkdownOptions {
    fn default() -> Self {
        ToMarkdownOptions {
            image_output_dir: NullableString::default(),
            image: NullableString::default(),
            use_html: false,
            include_version: false,
            include_page_info: false,
        }
    }
}

impl Default for ToMarkdownResult {
    fn default() -> Self {
        ToMarkdownResult {
            markdown: String::default(),
        }
    }
}

impl Default for ToPdfOptions {
    fn default() -> Self {
        ToPdfOptions {
            font_dir: NullableString::default(),
            embed_images: true,
        }
    }
}
