// Auto generated by Craby. DO NOT EDIT.
// Hash: 5ad476cbef44daa0
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait HwpjsSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn file_header(&mut self, data: Array<Number>) -> String;
    fn to_json(&mut self, data: Array<Number>) -> String;
    fn to_markdown(&mut self, data: Array<Number>, options: ToMarkdownOptions) -> ToMarkdownResult;
}

impl Default for NullableString {
    fn default() -> Self {
        NullableString {
            null: true,
            val: String::default(),
        }
    }
}

impl From<NullableString> for Nullable<String> {
    fn from(val: NullableString) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<String>> for NullableString {
    fn from(val: Nullable<String>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableString {
            val: val.unwrap_or(String::default()),
            null,
        }
    }
}

impl Default for ToMarkdownOptions {
    fn default() -> Self {
        ToMarkdownOptions {
            image_output_dir: NullableString::default(),
            image: NullableString::default(),
            use_html: false,
            include_version: false,
            include_page_info: false
        }
    }
}

impl Default for ToMarkdownResult {
    fn default() -> Self {
        ToMarkdownResult {
            markdown: String::default()
        }
    }
}
