/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Parse HWP file from byte array (Buffer or Uint8Array)
 *
 * # Arguments
 * * `data` - Byte array containing HWP file data
 *
 * # Returns
 * Parsed HWP document as JSON string
 */
export declare function parseHwp(data: Array<number>): string

/**
 * Parse HWP file and return only FileHeader as JSON
 *
 * # Arguments
 * * `data` - Byte array containing HWP file data
 *
 * # Returns
 * FileHeader as JSON string
 */
export declare function parseHwpFileheader(data: Array<number>): string

export declare function plus100(input: number): number
