const std = @import("std");
const core = @import("hwpjs");
const int = @import("resource-probe.zig").int;
pub fn run(a: std.mem.Allocator, bytes: []const u8, limit: usize) ![]u8 {
    var input: core.Reader = .{ .bytes = bytes };
    const max_objects = try input.readInt(u32);
    const axes = try input.readInt(u32);
    const lines = try input.readInt(u32);
    const count = try input.readInt(u32);
    if (count > 16) return error.LimitExceeded;
    var points: [16]usize = undefined;
    for (points[0..count]) |*n| n.* = try input.readInt(u32);
    var value = try core.hwp5.chart_observed_contents.readObservedV6(a, bytes[input.offset..], .{ .primary_axis_count = axes, .line_item_count = lines, .series_point_counts = points[0..count] }, .{ .prefix = .{ .grid = .{ .prelude = .{ .max_bytes = limit } }, .objects = .{ .max_objects = max_objects } } });
    defer value.deinit();
    var point_count: usize = 0;
    for (value.series.items) |item| point_count += item.section.points.len;
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(a);
    inline for (.{ value.end, value.prefix.grid.prelude.types.definitions.count(), value.prefix.objects.entries.count(), value.prefix.objects.string_bytes, value.primary_axes.len, value.line_items.len, value.series.items.len, point_count, value.light.sources.len }) |n| try int(a, &out, u32, @intCast(n));
    try out.appendSlice(a, &value.prefix.transition.raw);
    try out.appendSlice(a, &value.tail.raw);
    const type_count = value.prefix.grid.prelude.types.definitions.count();
    const series = try @import("chart-series-collection-probe.zig").serialize(a, value.series, type_count, &value.prefix.objects);
    defer a.free(series);
    try out.appendSlice(a, series);
    const title = try @import("chart-title-body-probe.zig").serialize(a, value.series.title.object_id, value.title, type_count, &value.prefix.objects);
    defer a.free(title);
    try out.appendSlice(a, title);
    for (value.primary_axes) |axis| try @import("chart-axes-probe.zig").serialize(a, &out, axis, &value.prefix.objects);
    try @import("chart-axes-probe.zig").serialize(a, &out, value.secondary_axis, &value.prefix.objects);
    const object_count = value.prefix.objects.entries.count();
    const light = try @import("chart-light-probe.zig").serialize(a, value.light, object_count);
    defer a.free(light);
    try out.appendSlice(a, light);
    const line_end = if (value.line_items.len > 0) value.line_items[value.line_items.len - 1].end else value.secondary_axis.end + @sizeOf(u16);
    const lines_wire = try @import("chart-line-items-probe.zig").serialize(a, value.line_word, value.line_items, line_end, type_count, object_count);
    defer a.free(lines_wire);
    try out.appendSlice(a, lines_wire);
    const post_line = try @import("chart-post-line-probe.zig").serialize(a, value.post_line, type_count, object_count);
    defer a.free(post_line);
    try out.appendSlice(a, post_line);
    const types = &value.prefix.grid.prelude.types;
    const objects = &value.prefix.objects;
    try @import("chart-plot-surface-probe.zig").appendPlot(a, &out, value.plot, types, objects);
    try @import("chart-plot-surface-probe.zig").appendSurface(a, &out, value.surface, types, objects);
    const tail = try @import("chart-tail-probe.zig").serialize(a, value.tail, type_count, object_count);
    defer a.free(tail);
    try out.appendSlice(a, tail);
    // Redundant component boundaries still belong to the returned value.
    inline for (.{ value.tail.list.collection.end, value.tail.window.end, value.light.array.end }) |end| try int(a, &out, u32, @intCast(end));
    for (value.series.items) |item| {
        try int(a, &out, u32, @intCast(item.section.end));
        try int(a, &out, u32, @intCast(item.suffix.end));
    }
    const grid = try @import("chart-grid-cells-probe.zig").serialize(a, value.prefix.grid);
    defer a.free(grid);
    try out.appendSlice(a, grid);
    const prelude = try @import("chart-grid-prelude-probe.zig").serialize(a, value.prefix.grid.prelude);
    defer a.free(prelude);
    try out.appendSlice(a, prelude);
    const footnote = try @import("chart-footnote-probe.zig").serialize(a, value.prefix.footnote);
    defer a.free(footnote);
    try out.appendSlice(a, footnote);
    const legend = try @import("chart-legend-probe.zig").serialize(a, value.prefix.legend, object_count, value.prefix.objects.string_bytes);
    defer a.free(legend);
    try out.appendSlice(a, legend);
    inline for (.{ value.prefix.footnote.section.end, value.prefix.footnote.section.backdrop.end, value.prefix.legend.section.end, value.prefix.legend.section.backdrop.end, value.prefix.end }) |end| try int(a, &out, u32, @intCast(end));
    const transition = value.prefix.transition;
    const backdrop = try @import("chart-backdrop-probe.zig").serialize(a, transition.backdrop, transition.raw);
    defer a.free(backdrop);
    try out.appendSlice(a, backdrop);
    try int(a, &out, u32, @intCast(transition.end));
    try @import("chart-type-table-wire.zig").append(a, &out, types);
    try @import("chart-object-table-wire.zig").append(a, &out, objects);
    const footnote_block = value.prefix.footnote.block;
    inline for (.{ footnote_block.font.name_introduced, footnote_block.text_introduced, footnote_block.backdrop != null }) |flag|
        try int(a, &out, u32, @intFromBool(flag));
    return out.toOwnedSlice(a);
}
