// Placeholder TypeScript wrapper
// This will be properly generated by NAPI-RS

/**
 * HWP file reader for Node.js
 *
 * This is a placeholder implementation.
 * The actual bindings will be generated by NAPI-RS.
 */

export const hello = (): string => {
  return 'Hello from hwp-node TypeScript!';
};

export default {
  hello,
};
